name: Build Container Images

on:
  workflow_dispatch:
    inputs:
      tachidesk_release_type:
        required: true
        default: 'preview'
        description: 'Suwayomi Release Type'
        type: choice
        options:
          - stable
          - preview

jobs:
  go:
    uses: ./.github/workflows/container.yml
    with:
      tachidesk_release_type: ${{ inputs.tachidesk_release_type }}
      do_upload: true
    secrets: inherit
